language: ruby

#travis workaround for bundler failing on 1.8.7
before_install:
  - gem update --system 2.1.11
  - gem --version

install:
  - gem install

rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7

script: rake ci

